variable "subnet_1" {}
variable "subnet_2" {}
#variable "subnets" {type="list"}
variable "office_ip" {}
variable "dns_zone_id" {}
variable "dns_zone_name" {}
variable "image_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "volume_type" {}
variable "volume_size" {}